# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4707df931f50d99dc540ab5f2b318f320dd12823331b607899fb89362ecec512f7a27e7d75483c87fee87de9a263e0cca068b303775300a439d3c1c6d6c7da39

test:
  secret_key_base: 29d0d7fb98b3480bdbb469719fac9c8ef41ae10222162925dcd3d41ca07142fa0bdb710b4ed7779f15a0ae8fa87b5f8bc3a592d47693f14c03bf50c4a10babec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
